small update
phaser-discord/community pull request #4
Opened 2019-02-21 21:59 UTC by KingCosmic

updated scale manager and added a resources page for commonly used links and such

2019-02-22 10:18 UTC, 16patsle requested changes

2019-02-22 10:18 UTC, 16patsle commented on RESOURCES.md
> +this is a list of resources useful in your gamedevelopment with phaser
Maybe create a heading?

2019-02-22 15:13 UTC, jdotrjs requested changes

2019-02-22 15:13 UTC, jdotrjs commented on FAQ.md
> -_Last Updated: 2018-12-07_
Don't entirely drop the previous writeup; 3.16 comes with scale manager but it's worth leaving pointers to the examples in the event that folks are stuck < 3.16 for some reason.

2019-02-22 15:13 UTC, jdotrjs commented on RESOURCES.md
> +this is a list of resources useful in your gamedevelopment with phaser
> Maybe create a heading?

👍 

`# Resources`

2019-02-22 15:13 UTC, jdotrjs commented on RESOURCES.md
> +[Tile Extruder][te] this tool helps you extrude your tiles to solve the issue of tile bleeding.
Make this a list

2019-03-24 19:50 UTC, 16patsle commented
@KingCosmic Planning on doing something here, or should we just let it rot until I find out I have time to do it myself?

2019-03-29 22:03 UTC, KingCosmic commented
sorry I've been busy, had something that popped up earlier this month and will be off my plate this monday I can look into fixing it then if that's fine

2019-03-29 22:16 UTC, KingCosmic commented
I fixed the requested changes, sorry for the lateness as I said had something pop up.

2019-03-30 10:05 UTC, 16patsle approved these changes

2019-03-30 10:05 UTC, 16patsle commented
Thanks :smile:

2019-04-02 06:20 UTC, jdotrjs approved these changes

2019-04-02 06:20 UTC, merged